version: "3"
services:
  realestate:
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    networks:
      - redis
    links:
      - redis
  redis-db:
    image: redis
    networks:
      - redis
networks:
  redis:
    driver: bridge
